### ISSUE TITLE
Support infinite/recursive types

### ISSUE THREAD

**Issue by puffnfresh** [puffnfresh/type-algebra#1]
e.g.

```
forall a. (a -> a) -> a -> a
= infinity
```

**Comment by puffnfresh** [comment]
Part of this page discusses infinite inhabitants, sadly formatting is a bit broken:

https://web.archive.org/web/20201111192703/https://alexknvl.com/posts/counting-type-inhabitants.html

Here is a screenshot with formatting fixed:

![image](https://github.com/puffnfresh/type-algebra/assets/37715/5c10df3a-7b75-4689-b2ec-eb2ee546cb74)

In terms of code, the first thing we'll need to create some sort of cardinality type, with infinite being a possibility:

https://gitlab.com/cokeice/tc/-/blob/42f23a8998462f163c62b6028e8c4469de06eab8/typealg/src/main/scala/com/alexknvl/counting/Cardinality.scala#L49-50

Then we need to do the check as described above.

**Comment by freeman42x** [comment]
@puffnfresh an image of documentation and code haha.

can you please link to where it is? or just paste entire markdown of it in markdown code block

![](https://media.giphy.com/media/W3a0zO282fuBpsqqyD/giphy.gif)

**Comment by puffnfresh** [comment]
I did link it.

**Comment by freeman42x** [comment]
> I did link it.

That makes me have even more questions. 🤔😆 Anyways, will start work on it in a bit. 💝

**Comment by puffnfresh** [comment]
We'll need to introduce `Mu`, and add a rewrite from `Forall` when the pattern described in that blog post is detected. Maybe we don't need to add a `Cardinality` type - we can just detect the use of `Mu`.

**Comment by puffnfresh** [comment]
Implemented something which seems to work for some cases in b04d58b0acc721306fcc75484a657a06ccd79fc5.
